name: Auto approve
on: pull_request_target

jobs:
  auto_approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Auto approve PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          const github = require('@actions/github');
          const octokit = new github.getOctokit('${{ secrets.GITHUB_TOKEN }}');
          
          const { owner, repo, number } = github.context.issue;
          octokit.pulls.createReview({
            owner,
            repo,
            pull_number: number,
            event: 'APPROVE'
          });
